version: 2
jobs:
  build:
    working_directory: ~/{{cookiecutter.app_name}}
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            virtualenv env
            source env/bin/activate
            pip install -r dev_requirements.txt
            flake8 . --exclude=env,migrations/
